# Site settings
title: Stephen Mitchell
email: your-email@domain.com
url: http://stephenmitchell.me.uk
description: "Software developer with around 6 years of industry experience and
a degree in Computer Science from Northumbria University. Located in Sunderland,
UK. Currently seeking a full-time permanent position either within commuting
distance of Sunderland or in Leeds, West Yorkshire."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Stephen Mitchell

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/stephenamitchell
  - title: twitter
    url: https://twitter.com/stephenmitchell
  - title: facebook
    url: https://www.facebook.com/stephen.mitchell
  - title: github
    url: https://github.com/stephen-mitchell

# Build settings
markdown: kramdown
permalink: pretty
