# Site settings
title: Stephen Mitchell
email: your-email@domain.com
url: http://stephenmitchell.me.uk
description: "Senior software developer with over 10 years of industry experience and a degree in Computer Science from Northumbria University. Born and raised in Sunderland, currently living and working in Leeds, West Yorkshire."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Stephen Mitchell

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/stephenamitchell
  - title: twitter
    url: https://twitter.com/stephenmitchell
  - title: facebook
    url: https://www.facebook.com/stephen.mitchell
  - title: github
    url: https://github.com/stephen-mitchell
  - title: mastodon
    url: https://yorkshire.social/@stephenmitchell

# Build settings
markdown: kramdown
permalink: pretty
